# This is a basic workflow to help you get started with Actions

name: CI SERIAL MU

########################################################################
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # Comment lines 10-13 to deactivate automatic running until Metis webpage is online again.
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Permissions for codecov
    permissions:
      id-token: write
      contents: read

    # Define strategy matrix
    strategy:
      fail-fast: false
      matrix:
        compiler: ['gfortran']
        mode: ['DEBUG']
        comm: ['SEQUENTIAL']
        enable_threads: ['NO']

    name: MU - ${{ matrix.compiler }} - ${{ matrix.mode }} - ${{ matrix.comm }} - ${{ matrix.enable_threads }}

    env:
      INTEL_COMPILER_DIR : /opt/intel/oneapi/compiler/2024.1
    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set Coverage Flags
        run: |
          if [ "${{ matrix.mode }}" = "DEBUG" ]; then
            echo "EXTRA_COV=-Og -fprofile-arcs -ftest-coverage" >> $GITHUB_ENV
          else
            echo "EXTRA_COV=" >> $GITHUB_ENV
          fi

      # IF COMPILER = IFORT -> INSTALL IFORT #
      # UNCOMMENT TO USE CACHED IFORT 
      #- name: cache-intel-compilers
      #  if: (matrix.compiler == 'ifort')
      #  id: cache-intel-compilers
      #  uses: actions/cache@v3
      #  with:
      #    path: /opt/intel
      #    key: intel-${{ runner.os }}-compilers-b

      - name: Intel Apt repository
      # UNCOMMENT TO USE CACHED IFORT 
      #  if: (steps.cache-intel-compilers.outputs.cache-hit != 'true')
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
          sudo apt-get update

      - name: Install Intel oneAPI
      # UNCOMMENT TO USE CACHED IFORT
      #  if: (steps.cache-intel-compilers.outputs.cache-hit != 'true')
        run: sudo apt-get install intel-oneapi-compiler-fortran intel-oneapi-compiler-dpcpp-cpp intel-oneapi-mkl-devel ninja-build

      # Runs a single command using the runners shell
      ##- name: Install gfortran
      ##  run: |
      ##   sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      ##   sudo apt update
      ##   sudo apt-get install gfortran-9

      ##- name: Show gfortran version
      ##  run: gfortran-9 --version
      - name: Show ${{matrix.compiler}} version
        run: |
          source /opt/intel/oneapi/setvars.sh || true
          ${{matrix.compiler}} --version

      - name: Configure
        working-directory: ./Solver
        run: ./configure

      - name: Compile horses3d
        working-directory: ./Solver
        run: |
         source /opt/intel/oneapi/setvars.sh || true
         make allclean MODE=${{matrix.mode}} COMPILER=${{matrix.compiler}} COMM=${{matrix.comm}} ENABLE_THREADS=${{matrix.enable_threads}} WITH_METIS=NO EXTRA_FFLAGS="${{ env.EXTRA_COV }}"
         make mu MODE=${{matrix.mode}} COMPILER=${{matrix.compiler}} COMM=${{matrix.comm}} ENABLE_THREADS=${{matrix.enable_threads}} WITH_METIS=NO EXTRA_FFLAGS="${{ env.EXTRA_COV }}"


# ########################################################################
# #######                       MULTIPHASE                        ########
# ########################################################################
# #
# # 1) Convergence
# # ----------------------------

#       - name: Build MultiphaseConvergence
#         working-directory: ./Solver/test/Multiphase/Convergence/SETUP
#         run: |
#           source /opt/intel/oneapi/setvars.sh || true
#           make MODE=${{matrix.mode}} COMPILER=${{matrix.compiler}} COMM=${{matrix.comm}} ENABLE_THREADS=${{matrix.enable_threads}} WITH_METIS=YES EXTRA_FFLAGS="${{ env.EXTRA_COV }}"

#       - name: Run MultiphaseConvergence
#         working-directory: ./Solver/test/Multiphase/Convergence
#         run: |
#           source /opt/intel/oneapi/setvars.sh || true
#           mpiexec -n 64 ./horses3d.mu Convergence.control

# #
# # 2) RisingBubble
# # ----------------------------

#       - name: Build MultiphaseRisingBubble
#         working-directory: ./Solver/test/Multiphase/RisingBubble/SETUP
#         run: |
#           source /opt/intel/oneapi/setvars.sh || true
#           make MODE=${{matrix.mode}} COMPILER=${{matrix.compiler}} COMM=${{matrix.comm}} ENABLE_THREADS=${{matrix.enable_threads}} WITH_METIS=YES EXTRA_FFLAGS="${{ env.EXTRA_COV }}"

#       - name: Run MultiphaseRisingBubble
#         working-directory: ./Solver/test/Multiphase/RisingBubble
#         run: |
#           source /opt/intel/oneapi/setvars.sh || true
#           mpiexec -n 64 ./horses3d.mu RisingBubble.control

# #
# # 3) Pipe
# # ----------------------------

#       - name: Build MultiphasePipe
#         working-directory: ./Solver/test/Multiphase/Pipe/SETUP
#         run: |
#           source /opt/intel/oneapi/setvars.sh || true
#           make MODE=${{matrix.mode}} COMPILER=${{matrix.compiler}} COMM=${{matrix.comm}} ENABLE_THREADS=${{matrix.enable_threads}} WITH_METIS=YES EXTRA_FFLAGS="${{ env.EXTRA_COV }}"

#       - name: Run MultiphasePipe
#         working-directory: ./Solver/test/Multiphase/Pipe
#         run: |
#           source /opt/intel/oneapi/setvars.sh || true
#           mpiexec -n 64 ./horses3d.mu AnnularFlow.control

#
# 4) Entropy conserving test
# ----------------------------

      - name: Build MultiphaseEntropyConservingTest
        working-directory: ./Solver/test/Multiphase/EntropyConservingTest/SETUP
        run: |
          source /opt/intel/oneapi/setvars.sh || true
          make mu MODE=${{matrix.mode}} COMPILER=${{matrix.compiler}} COMM=${{matrix.comm}} ENABLE_THREADS=${{matrix.enable_threads}} WITH_METIS=NO EXTRA_FFLAGS="${{ env.EXTRA_COV }}"

      - name: Run MultiphaseEntropyConservingTest
        working-directory: ./Solver/test/Multiphase/EntropyConservingTest
        run: |
          source /opt/intel/oneapi/setvars.sh || true
          ./horses3d.mu EntropyConservingTest.control

#
# 5) Multiphase monopole with acoustics, sponge and Reinforcement Learning p-adaptation
# --------------------------------------------
# GPU
      # - name: Build Multiphase_Monopole_pAdaptationRL
      #   working-directory: ./Solver/test/Multiphase/Monopole_pAdaptationRL/SETUP
      #   run: |
      #     source /opt/intel/oneapi/setvars.sh || true
      #     make mu MODE=${{matrix.mode}} COMPILER=${{matrix.compiler}} COMM=${{matrix.comm}} ENABLE_THREADS=${{matrix.enable_threads}} WITH_METIS=YES
      #   if: '!cancelled()'

      # - name: Run Multiphase_Monopole_pAdaptationRL
      #   working-directory: ./Solver/test/Multiphase/Monopole_pAdaptationRL
      #   run: |
      #     source /opt/intel/oneapi/setvars.sh || true
      #     mpiexec -n 64 ./horses3d.mu monopole_pAdaptationRL.control
      #   if: '!cancelled()'

#
# 6) Mu AL
# -------------------------------

  # GPU
      # - name: Build Mu-AL
      #   working-directory: ./Solver/test/Multiphase/ActuatorLineInterpolation/SETUP
      #   run: |
      #     source /opt/intel/oneapi/setvars.sh || true
      #     make mu MODE=${{matrix.mode}} COMPILER=${{matrix.compiler}} COMM=${{matrix.comm}} ENABLE_THREADS=${{matrix.enable_threads}} WITH_METIS=YES
      #   if: '!cancelled()'

      # - name: Run Mu-AL
      #   working-directory: ./Solver/test/Multiphase/ActuatorLineInterpolation
      #   run: |
      #     source /opt/intel/oneapi/setvars.sh || true
      #     mpiexec -n 64 ./horses3d.mu Actuator.control
      #   if: '!cancelled()'

#
# 7) Snell
# ----------------------------
# GPU
      # - name: Build MultiphaseSnell
      #   working-directory: ./Solver/test/Multiphase/Snell/SETUP
      #   run: |
      #     source /opt/intel/oneapi/setvars.sh || true
      #     make mu MODE=${{matrix.mode}} COMPILER=${{matrix.compiler}} COMM=${{matrix.comm}} ENABLE_THREADS=${{matrix.enable_threads}} WITH_METIS=YES
      #   if: '!cancelled()'

      # - name: Run MultiphaseSnell
      #   working-directory: ./Solver/test/Multiphase/Snell
      #   run: |
      #     source /opt/intel/oneapi/setvars.sh || true
      #     mpiexec -n 64 ./horses3d.mu snell.control
      #   if: '!cancelled()'

#
# 8) Mixed RK
# ----------------------------
# GPU
      # - name: Build MultiphaseMixedRK
      #   working-directory: ./Solver/test/Multiphase/MixedRK/SETUP
      #   run: |
      #     source /opt/intel/oneapi/setvars.sh || true
      #     make mu MODE=${{matrix.mode}} COMPILER=${{matrix.compiler}} COMM=${{matrix.comm}} ENABLE_THREADS=${{matrix.enable_threads}} WITH_METIS=YES
      #   if: '!cancelled()'

      # - name: Run MultiphaseMixedRK
      #   working-directory: ./Solver/test/Multiphase/MixedRK
      #   run: |
      #     source /opt/intel/oneapi/setvars.sh || true
      #     mpiexec -n 64 ./horses3d.mu mixedRK.control
      #   if: '!cancelled()'

#
# CHECK CODE COVERAGE
# -------------------------

      - name: Install gcovr
        if: matrix.mode == 'DEBUG' && !cancelled()
        run: |
          sudo apt-get update
          sudo apt-get install -y gcovr

      - name: Generate Coverage Report
        if: matrix.mode == 'DEBUG' && !cancelled()
        run: |
          # gcovr scans recursively from the root to find all generated .gcda and .gcno files
          gcovr --root . --print-summary --xml coverage.xml

      - name: Upload Coverage to Codecov
        if: matrix.mode == 'DEBUG' && !cancelled()
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          use_oidc: true